"""Add student OD request system

Revision ID: 0f7f977eb471
Revises: f2436d05e110
Create Date: 2026-02-12 13:55:37.297319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7f977eb471'
down_revision = 'f2436d05e110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_od_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('session_ids', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('supporting_document', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', 'CANCELLED', name='odrequeststatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_remarks', sa.String(length=500), nullable=True),
    sa.Column('approved_od_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_od_id'], ['approved_od_requests.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_od_requests', schema=None) as batch_op:
        batch_op.create_index('idx_student_od_class', ['class_id'], unique=False)
        batch_op.create_index('idx_student_od_dates', ['from_date', 'to_date'], unique=False)
        batch_op.create_index('idx_student_od_requested_at', ['requested_at'], unique=False)
        batch_op.create_index('idx_student_od_status', ['status'], unique=False)
        batch_op.create_index('idx_student_od_student', ['student_id'], unique=False)

    with op.batch_alter_table('approved_od_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_request_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_od_applied', ['applied'], unique=False)
        batch_op.create_index('idx_od_class', ['class_id'], unique=False)
        batch_op.create_index('idx_od_class_date', ['class_id', 'date'], unique=False)
        batch_op.create_index('idx_od_date', ['date'], unique=False)
        batch_op.create_index('idx_od_student', ['student_id'], unique=False)
        batch_op.create_index('idx_od_student_request', ['student_request_id'], unique=False)
        batch_op.create_foreign_key(None, 'student_od_requests', ['student_request_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_marked_at', ['marked_at'], unique=False)
        batch_op.create_index('idx_attendance_session', ['session_id'], unique=False)
        batch_op.create_index('idx_attendance_status', ['status'], unique=False)
        batch_op.create_index('idx_attendance_student', ['student_id'], unique=False)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_logs_attendance', ['attendance_id'], unique=False)
        batch_op.create_index('idx_attendance_logs_changed_at', ['changed_at'], unique=False)

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_class_date', ['class_id', 'date'], unique=False)
        batch_op.create_index('idx_sessions_date', ['date'], unique=False)
        batch_op.create_index('idx_sessions_faculty_date', ['faculty_id', 'date'], unique=False)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index('idx_classes_dept_year', ['department', 'year'], unique=False)

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_index('idx_faculty_department', ['department'], unique=False)
        batch_op.create_index('idx_faculty_user', ['user_id'], unique=False)

    with op.batch_alter_table('faculty_subject_class', schema=None) as batch_op:
        batch_op.create_index('idx_fsc_class', ['class_id'], unique=False)
        batch_op.create_index('idx_fsc_faculty', ['faculty_id'], unique=False)
        batch_op.create_unique_constraint('uix_faculty_subject_class', ['faculty_id', 'subject_id', 'class_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_students_class', ['class_id'], unique=False)
        batch_op.create_index('idx_students_department', ['department'], unique=False)
        batch_op.create_index('idx_students_roll_no', ['roll_no'], unique=False)
        batch_op.create_index('idx_students_user', ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index('idx_subjects_code', ['code'], unique=False)
        batch_op.create_index('idx_subjects_semester', ['semester'], unique=False)

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.create_index('idx_timetable_day', ['day_of_week'], unique=False)
        batch_op.create_index('idx_timetable_faculty', ['faculty_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_role', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_email')

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_index('idx_timetable_faculty')
        batch_op.drop_index('idx_timetable_day')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index('idx_subjects_semester')
        batch_op.drop_index('idx_subjects_code')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_students_user')
        batch_op.drop_index('idx_students_roll_no')
        batch_op.drop_index('idx_students_department')
        batch_op.drop_index('idx_students_class')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('faculty_subject_class', schema=None) as batch_op:
        batch_op.drop_constraint('uix_faculty_subject_class', type_='unique')
        batch_op.drop_index('idx_fsc_faculty')
        batch_op.drop_index('idx_fsc_class')

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_index('idx_faculty_user')
        batch_op.drop_index('idx_faculty_department')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index('idx_classes_dept_year')

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_faculty_date')
        batch_op.drop_index('idx_sessions_date')
        batch_op.drop_index('idx_sessions_class_date')

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_logs_changed_at')
        batch_op.drop_index('idx_attendance_logs_attendance')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_student')
        batch_op.drop_index('idx_attendance_status')
        batch_op.drop_index('idx_attendance_session')
        batch_op.drop_index('idx_attendance_marked_at')

    with op.batch_alter_table('approved_od_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_od_student_request')
        batch_op.drop_index('idx_od_student')
        batch_op.drop_index('idx_od_date')
        batch_op.drop_index('idx_od_class_date')
        batch_op.drop_index('idx_od_class')
        batch_op.drop_index('idx_od_applied')
        batch_op.drop_column('student_request_id')

    with op.batch_alter_table('student_od_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_student_od_student')
        batch_op.drop_index('idx_student_od_status')
        batch_op.drop_index('idx_student_od_requested_at')
        batch_op.drop_index('idx_student_od_dates')
        batch_op.drop_index('idx_student_od_class')

    op.drop_table('student_od_requests')
    # ### end Alembic commands ###
