"""SystemSettings

Revision ID: 6933603af3eb
Revises: 0f7f977eb471
Create Date: 2026-04-08 00:29:34.731257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6933603af3eb'
down_revision = '0f7f977eb471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_auto_generate_sessions', sa.Boolean(), nullable=False),
    sa.Column('current_term_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
