"""Add unique constraint to class_sessions

Revision ID: f2436d05e110
Revises: 
Create Date: 2026-01-25 21:42:03.499653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2436d05e110'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_od_requests', schema=None) as batch_op:
        batch_op.alter_column('approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_od_requests_class_date'))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_session_id_student_id_key'), type_='unique')
        batch_op.create_unique_constraint('uix_session_student', ['session_id', 'student_id'])

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.alter_column('attendance_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_session_unique', ['faculty_id', 'subject_id', 'class_id', 'date', 'start_time', 'end_time'])

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('timetables_subject_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('timetables_faculty_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('timetables_faculty_id_fkey'), 'faculties', ['faculty_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('timetables_subject_id_fkey'), 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('faculty_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('uix_session_unique', type_='unique')

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.alter_column('attendance_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uix_session_student', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('attendance_session_id_student_id_key'), ['session_id', 'student_id'])

    with op.batch_alter_table('approved_od_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_od_requests_class_date'), ['class_id', 'date'], unique=False)
        batch_op.alter_column('applied_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
